# User configuration file

general:
  tile_size: (2400, 2000)
  geom_verification: pydegensac
  gv_threshold: 1
  min_inliers_per_pair: 10
  min_inlier_ratio_per_pair: 0.25

extractor:
  name: "keynetaffnethardnet"
  n_features: 8000
  upright: False

matcher:
  name: "kornia_matcher"
  match_mode: "smnn"
  th: 0.95
